name: Deploy

on:
  push:
    branches: [main]

env:
  DOCKER_BUILDKIT: 1

jobs:
  publish-container-images:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GH_REGISTRY }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull latest
        run: docker pull ghcr.io/equinor/for:latest
      - name: Build
        run: docker build . --tag ghcr.io/equinor/for:latest --cache-from ghcr.io/equinor/for:latest
      - name: Push
        run: docker push ghcr.io/equinor/for:latest

  deploy-to-radix:
    needs: [publish-container-images]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy on Radix
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job
            deploy
            --context production
            --from-config
            -e prod
            -f
